version: '3'
services:
  # db:
    # image: mysql:5.7
    # environment:
      # MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: user
      # MYSQL_PASSWORD: 1234
      # MYSQL_DATABASE: myapp_db
    # volumes:
      # - mysql-data:/var/lib/mysql
    # ports:
      # - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/ulapp
      - public-data:/ulapp/public
      - tmp-data:/ulapp/tmp
      - log-data:/ulapp/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/ulapp/public
      - tmp-data:/ulapp/tmp
    ports:
      - 80:80

volumes:
  # mysql-data:
  public-data:
  tmp-data:
  log-data: