version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install      
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: sudo pip install awscli
      - run:
          name: SSH経由のデプロイ
          command: |
            ./shells/deploy.sh
      - add_ssh_keys:
          fingerprints:
            -"70:44:99:ca:99:4b:22:70:28:d5:14:db:c2:55:53:7e"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ulapp && git pull'

workflows:
    version: 2
    # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
    build_and_deploy:
        # build ジョブと deploy ジョブを呼び出す
        jobs:
            - build
            - deploy:
                requires:
                    # deploy ジョブより先に build ジョブを実行しろ、という命令
                    - build
                # master ブランチに push された場合のみ deploy ジョブを実行する
                filters:
                    branches:
                        only: production